version: '3'
services:
  web:
    container_name: web
    ports:
     - "127.0.0.1:8080:80"
     - "127.0.0.1:8443:443"
     - "127.0.0.1:8021:21"
     - "127.0.0.1:8022:22"
    image: "theraw/web-pro:web"
    privileged: true
    restart: unless-stopped
    shm_size: 512MB
    cap_add:
     - ALL
    networks:
      web_pro_net:
        ipv4_address: 172.69.0.70
    command: ["nginx", "-g", "daemon off;"]

  php73:
    container_name: php73
    ports:
     - "127.0.0.1:9000:9000"
     - "127.0.0.1:9002:9002"
     - "127.0.0.1:9004:9004"
     - "127.0.0.1:9006:9006"
    image: "theraw/web-pro:php73"
    privileged: true
    restart: unless-stopped
    shm_size: 512MB
    cap_add:
     - ALL
    networks:
      web_pro_net:
        ipv4_address: 172.69.0.90
    command: /sbin/init

  mysql:
    container_name: mysql
    ports:
     - "127.0.0.1:8090:80"
     - "127.0.0.1:3306:3306"
    image: "theraw/web-pro:mysql"
    privileged: true
    restart: unless-stopped
    shm_size: 512MB
    cap_add:
     - ALL
    networks:
      web_pro_net:
        ipv4_address: 172.69.0.72
    command: /usr/bin/mysqld --user=mysql --console --skip-name-resolve --skip-networking=0

networks:
  web_pro_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.69.0.0/16
